# 13 Código para Redes Neuronales FC

In [1]:
import torch 
import torch.nn as nn

## Vector de entrada

Pensemos que R es un vector en R5 y queremos contruir una red neuronal pequeñísima que termine con un vector en R3.
En PyTorch todo funciona en batches, supongamos que son de tamaño 4 (4 datos diferentes)

In [3]:
bs = 4
n  = 5

x = torch.rand( bs,n ) #Esto se debe obetner de los datos

$x$ son los datos

## Creado la red

nn es la parte de Pytorch para hacer redes neuronales

In [7]:
red_neuronal = nn.Sequential( #Espera que le pases una serie de módulos (redm neuronal, funcion con parámetros)
    nn.Linear( 5,10 ), #Transformacion afin de R5,en Rx. La inicializa con parámetro aleatorios
    nn.ReLU(),         #0 en los negativos, I en los positivos
    nn.Linear( 10,8 ), #Rx en Ry
    nn.LeakyReLU( negative_slope = 0.1 ), #Se puede tomar cualquier otra activacion
    nn.Linear( 8,3 )   #Regresamos a R3

)

## Usando la red neuronal

In [8]:
red_neuronal( x )

tensor([[-0.0076, -0.2148,  0.0017],
        [-0.0038, -0.2098, -0.0584],
        [-0.0329, -0.1512,  0.0338],
        [-0.0440, -0.1927,  0.0825]], grad_fn=<AddmmBackward>)

Regresa un tensor de tamaño batches, Rn ( 4,3 )

## Examinando la red neuronal

In [9]:
red_neuronal #La descrpcion de la red

Sequential(
  (0): Linear(in_features=5, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=8, bias=True)
  (3): LeakyReLU(negative_slope=0.1)
  (4): Linear(in_features=8, out_features=3, bias=True)
)

In [10]:
a = red_neuronal[0]

In [11]:
list( a.parameters() )

[Parameter containing:
 tensor([[-2.5622e-01,  4.0445e-01, -4.4465e-01,  2.5547e-01,  4.4100e-01],
         [-1.2133e-01, -4.2909e-01, -6.3142e-02, -3.7486e-01,  2.4321e-01],
         [ 1.3691e-01,  1.0272e-01, -3.8586e-01, -2.7694e-01, -3.0924e-01],
         [ 1.2613e-01,  2.7873e-01,  9.3108e-02, -2.5558e-04, -4.7704e-02],
         [-1.8774e-01,  6.7436e-02, -3.5561e-01, -1.0204e-01, -1.2345e-01],
         [ 2.8585e-01,  3.2892e-01, -4.1520e-01, -5.5921e-02,  2.1976e-02],
         [ 1.8414e-01, -3.6183e-01,  3.7364e-01,  2.4996e-01,  3.9545e-01],
         [-4.0820e-02, -3.2415e-01, -4.1490e-01, -2.6549e-01,  1.8770e-01],
         [ 7.0710e-02, -1.8556e-01, -1.5485e-02,  1.0934e-01, -2.4954e-01],
         [ 2.6336e-05, -9.4583e-02,  4.4218e-01,  2.8035e-01,  4.2404e-01]],
        requires_grad=True), Parameter containing:
 tensor([-0.2046, -0.3723,  0.3411, -0.0852,  0.3233,  0.2874, -0.1117,  0.0284,
         -0.0217, -0.2585], requires_grad=True)]

La matriz por la que multiplica y lo que le suma

In [12]:
list( a.parameters() )[0].shape

torch.Size([10, 5])

Matriz

Y es la matriz del primer parámtro de nuestra red
- nn.Linear( 5,10 ), 
- Transformacion afin de R5,en Rx. La inicializa con parámetro aleatorios

#### Si queremos pasar a la red neuronal un dato lo debemos hacer poniendo un paréntesis después

In [23]:
x = torch.randn( 8,8 )
x

tensor([[ 0.8260,  0.1246,  0.8131,  0.9116,  1.3249,  1.1975, -0.8852, -0.2763],
        [-0.4945,  0.0394,  0.9922,  0.7248, -0.9099,  1.1182, -0.3723, -1.4939],
        [ 1.0211, -0.5714,  0.4285, -0.6562,  1.9617, -1.3021, -0.1851,  0.4860],
        [-1.2957, -0.7853, -0.6806, -0.6593, -0.4933, -2.4669,  1.2801, -0.1489],
        [ 0.8636,  0.3587, -0.5643, -0.5384,  0.2180, -0.1899, -0.5483, -2.2484],
        [-1.2894, -0.6784,  0.9807,  0.1151, -1.2946,  0.1959,  1.1990,  0.0604],
        [ 1.2993,  1.7543,  0.3809,  0.5926,  0.0040, -0.2063,  1.1863,  0.5967],
        [ 0.2502, -0.3419, -0.2896, -0.1700,  1.4826, -0.8314, -0.6380, -0.1996]])

In [24]:
activacion = nn.ReLU()

In [25]:
activacion(x)

tensor([[0.8260, 0.1246, 0.8131, 0.9116, 1.3249, 1.1975, 0.0000, 0.0000],
        [0.0000, 0.0394, 0.9922, 0.7248, 0.0000, 1.1182, 0.0000, 0.0000],
        [1.0211, 0.0000, 0.4285, 0.0000, 1.9617, 0.0000, 0.0000, 0.4860],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.2801, 0.0000],
        [0.8636, 0.3587, 0.0000, 0.0000, 0.2180, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.9807, 0.1151, 0.0000, 0.1959, 1.1990, 0.0604],
        [1.2993, 1.7543, 0.3809, 0.5926, 0.0040, 0.0000, 1.1863, 0.5967],
        [0.2502, 0.0000, 0.0000, 0.0000, 1.4826, 0.0000, 0.0000, 0.0000]])

Los negativos los pone en 0

In [26]:
nn.ReLU()(x)

tensor([[0.8260, 0.1246, 0.8131, 0.9116, 1.3249, 1.1975, 0.0000, 0.0000],
        [0.0000, 0.0394, 0.9922, 0.7248, 0.0000, 1.1182, 0.0000, 0.0000],
        [1.0211, 0.0000, 0.4285, 0.0000, 1.9617, 0.0000, 0.0000, 0.4860],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.2801, 0.0000],
        [0.8636, 0.3587, 0.0000, 0.0000, 0.2180, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.9807, 0.1151, 0.0000, 0.1959, 1.1990, 0.0604],
        [1.2993, 1.7543, 0.3809, 0.5926, 0.0040, 0.0000, 1.1863, 0.5967],
        [0.2502, 0.0000, 0.0000, 0.0000, 1.4826, 0.0000, 0.0000, 0.0000]])