# Batchnorm
Normalizar para tener desviacion estandar de 1 y media de 0 después de cada capa

Pero no sabemos cuál es la media o std de la capa k, entonces usamos la media y la std de cada batch

La media y std son vectores con el mismo número de canales que $x$. Cada canal puede tener diferente media y desviación

¡Pero no vamos a poder predecir cosas con diferente media o std!

Entonces $Batchnorm$ decide independiemtemete otros dos parámetros, uno multiplicativo $\gamma$ y otro aditivo $\beta$ con el mismo número de canales que $x$

Inicilizamos como
- $\gamma$ vector de unos 
- $\beta$ vector de ceros

In [10]:
import torch
import torch.nn as nn

In [8]:
B = nn.BatchNorm1d( 20 )

1d para vectores (no para imágenes)

In [11]:
x = torch.rand( 64, 20 )
#batch_size 64 y de tamaño 20
B(x)

tensor([[-1.6935, -0.9846, -1.5932,  ..., -0.8760, -1.0148, -0.5973],
        [-0.8761,  0.9017,  0.6878,  ..., -0.6489, -0.9991,  0.0985],
        [ 0.8077, -0.2551, -0.8767,  ..., -0.8424, -0.0745, -0.8043],
        ...,
        [ 0.9356,  1.5005,  0.7621,  ...,  0.1580, -0.1781,  0.3653],
        [ 0.7895,  0.0960,  0.7687,  ..., -0.8140, -0.7490, -1.3115],
        [-1.2950,  0.9852, -0.0650,  ..., -1.0802,  1.0070, -1.3761]],
       grad_fn=<NativeBatchNormBackward>)

In [14]:
B.weight

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], requires_grad=True)

In [15]:
B.bias

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)

$\gamma$ y $\beta$ requieren gardiente porque después de entrenar la red ya van a cambiar sus valores

### ¿Cómo ponemos Batchnorm dentro de nuestra red?

In [17]:
nn.Sequential(nn.BatchNorm2d( 3 ), #Es ideal empezar normalizando los datos, además nos evitamos un paso anterior de normalizar
              nn.Conv2d( 3, 16, kernel_size = 3 ), 
              nn.ReLU(),
              nn.BatchNorm2d( 16 ), # Con el tamaño que sale de la transformación lineal
              nn.Conv2d( 16, 32, kernel_size = 3 ),
              nn.ReLU(),
              nn.BatchNorm2d( 32 )              
)

Sequential(
  (0): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1))
  (2): ReLU()
  (3): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (4): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1))
  (5): ReLU()
  (6): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

Regresa la estructura de la Red Neuronal

### Con Batchnorm aumentamos muchísimo la accuracy de nuestros modelos